// This file is generated by rust-protobuf 2.5.0. Do not edit
// @generated

// https://github.com/Manishearth/rust-clippy/issues/702
#![allow(unknown_lints)]
#![allow(clippy)]

#![cfg_attr(rustfmt, rustfmt_skip)]

#![allow(box_pointers)]
#![allow(dead_code)]
#![allow(missing_docs)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(trivial_casts)]
#![allow(unsafe_code)]
#![allow(unused_imports)]
#![allow(unused_results)]

use protobuf::Message as Message_imported_for_functions;
use protobuf::ProtobufEnum as ProtobufEnum_imported_for_functions;

#[derive(PartialEq,Clone,Default)]
pub struct Request {
    // message fields
    ID: ::std::option::Option<u64>,
    Method: ::protobuf::SingularField<::std::string::String>,
    Path: ::protobuf::SingularField<::std::string::String>,
    Val: ::protobuf::SingularField<::std::string::String>,
    Dir: ::std::option::Option<bool>,
    PrevValue: ::protobuf::SingularField<::std::string::String>,
    PrevIndex: ::std::option::Option<u64>,
    PrevExist: ::std::option::Option<bool>,
    Expiration: ::std::option::Option<i64>,
    Wait: ::std::option::Option<bool>,
    Since: ::std::option::Option<u64>,
    Recursive: ::std::option::Option<bool>,
    Sorted: ::std::option::Option<bool>,
    Quorum: ::std::option::Option<bool>,
    Time: ::std::option::Option<i64>,
    Stream: ::std::option::Option<bool>,
    Refresh: ::std::option::Option<bool>,
    // special fields
    pub unknown_fields: ::protobuf::UnknownFields,
    pub cached_size: ::protobuf::CachedSize,
}

impl<'a> ::std::default::Default for &'a Request {
    fn default() -> &'a Request {
        <Request as ::protobuf::Message>::default_instance()
    }
}

impl Request {
    pub fn new() -> Request {
        ::std::default::Default::default()
    }

    // optional uint64 ID = 1;


    pub fn get_ID(&self) -> u64 {
        self.ID.unwrap_or(0)
    }
    pub fn clear_ID(&mut self) {
        self.ID = ::std::option::Option::None;
    }

    pub fn has_ID(&self) -> bool {
        self.ID.is_some()
    }

    // Param is passed by value, moved
    pub fn set_ID(&mut self, v: u64) {
        self.ID = ::std::option::Option::Some(v);
    }

    // optional string Method = 2;


    pub fn get_Method(&self) -> &str {
        match self.Method.as_ref() {
            Some(v) => &v,
            None => "",
        }
    }
    pub fn clear_Method(&mut self) {
        self.Method.clear();
    }

    pub fn has_Method(&self) -> bool {
        self.Method.is_some()
    }

    // Param is passed by value, moved
    pub fn set_Method(&mut self, v: ::std::string::String) {
        self.Method = ::protobuf::SingularField::some(v);
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_Method(&mut self) -> &mut ::std::string::String {
        if self.Method.is_none() {
            self.Method.set_default();
        }
        self.Method.as_mut().unwrap()
    }

    // Take field
    pub fn take_Method(&mut self) -> ::std::string::String {
        self.Method.take().unwrap_or_else(|| ::std::string::String::new())
    }

    // optional string Path = 3;


    pub fn get_Path(&self) -> &str {
        match self.Path.as_ref() {
            Some(v) => &v,
            None => "",
        }
    }
    pub fn clear_Path(&mut self) {
        self.Path.clear();
    }

    pub fn has_Path(&self) -> bool {
        self.Path.is_some()
    }

    // Param is passed by value, moved
    pub fn set_Path(&mut self, v: ::std::string::String) {
        self.Path = ::protobuf::SingularField::some(v);
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_Path(&mut self) -> &mut ::std::string::String {
        if self.Path.is_none() {
            self.Path.set_default();
        }
        self.Path.as_mut().unwrap()
    }

    // Take field
    pub fn take_Path(&mut self) -> ::std::string::String {
        self.Path.take().unwrap_or_else(|| ::std::string::String::new())
    }

    // optional string Val = 4;


    pub fn get_Val(&self) -> &str {
        match self.Val.as_ref() {
            Some(v) => &v,
            None => "",
        }
    }
    pub fn clear_Val(&mut self) {
        self.Val.clear();
    }

    pub fn has_Val(&self) -> bool {
        self.Val.is_some()
    }

    // Param is passed by value, moved
    pub fn set_Val(&mut self, v: ::std::string::String) {
        self.Val = ::protobuf::SingularField::some(v);
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_Val(&mut self) -> &mut ::std::string::String {
        if self.Val.is_none() {
            self.Val.set_default();
        }
        self.Val.as_mut().unwrap()
    }

    // Take field
    pub fn take_Val(&mut self) -> ::std::string::String {
        self.Val.take().unwrap_or_else(|| ::std::string::String::new())
    }

    // optional bool Dir = 5;


    pub fn get_Dir(&self) -> bool {
        self.Dir.unwrap_or(false)
    }
    pub fn clear_Dir(&mut self) {
        self.Dir = ::std::option::Option::None;
    }

    pub fn has_Dir(&self) -> bool {
        self.Dir.is_some()
    }

    // Param is passed by value, moved
    pub fn set_Dir(&mut self, v: bool) {
        self.Dir = ::std::option::Option::Some(v);
    }

    // optional string PrevValue = 6;


    pub fn get_PrevValue(&self) -> &str {
        match self.PrevValue.as_ref() {
            Some(v) => &v,
            None => "",
        }
    }
    pub fn clear_PrevValue(&mut self) {
        self.PrevValue.clear();
    }

    pub fn has_PrevValue(&self) -> bool {
        self.PrevValue.is_some()
    }

    // Param is passed by value, moved
    pub fn set_PrevValue(&mut self, v: ::std::string::String) {
        self.PrevValue = ::protobuf::SingularField::some(v);
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_PrevValue(&mut self) -> &mut ::std::string::String {
        if self.PrevValue.is_none() {
            self.PrevValue.set_default();
        }
        self.PrevValue.as_mut().unwrap()
    }

    // Take field
    pub fn take_PrevValue(&mut self) -> ::std::string::String {
        self.PrevValue.take().unwrap_or_else(|| ::std::string::String::new())
    }

    // optional uint64 PrevIndex = 7;


    pub fn get_PrevIndex(&self) -> u64 {
        self.PrevIndex.unwrap_or(0)
    }
    pub fn clear_PrevIndex(&mut self) {
        self.PrevIndex = ::std::option::Option::None;
    }

    pub fn has_PrevIndex(&self) -> bool {
        self.PrevIndex.is_some()
    }

    // Param is passed by value, moved
    pub fn set_PrevIndex(&mut self, v: u64) {
        self.PrevIndex = ::std::option::Option::Some(v);
    }

    // optional bool PrevExist = 8;


    pub fn get_PrevExist(&self) -> bool {
        self.PrevExist.unwrap_or(false)
    }
    pub fn clear_PrevExist(&mut self) {
        self.PrevExist = ::std::option::Option::None;
    }

    pub fn has_PrevExist(&self) -> bool {
        self.PrevExist.is_some()
    }

    // Param is passed by value, moved
    pub fn set_PrevExist(&mut self, v: bool) {
        self.PrevExist = ::std::option::Option::Some(v);
    }

    // optional int64 Expiration = 9;


    pub fn get_Expiration(&self) -> i64 {
        self.Expiration.unwrap_or(0)
    }
    pub fn clear_Expiration(&mut self) {
        self.Expiration = ::std::option::Option::None;
    }

    pub fn has_Expiration(&self) -> bool {
        self.Expiration.is_some()
    }

    // Param is passed by value, moved
    pub fn set_Expiration(&mut self, v: i64) {
        self.Expiration = ::std::option::Option::Some(v);
    }

    // optional bool Wait = 10;


    pub fn get_Wait(&self) -> bool {
        self.Wait.unwrap_or(false)
    }
    pub fn clear_Wait(&mut self) {
        self.Wait = ::std::option::Option::None;
    }

    pub fn has_Wait(&self) -> bool {
        self.Wait.is_some()
    }

    // Param is passed by value, moved
    pub fn set_Wait(&mut self, v: bool) {
        self.Wait = ::std::option::Option::Some(v);
    }

    // optional uint64 Since = 11;


    pub fn get_Since(&self) -> u64 {
        self.Since.unwrap_or(0)
    }
    pub fn clear_Since(&mut self) {
        self.Since = ::std::option::Option::None;
    }

    pub fn has_Since(&self) -> bool {
        self.Since.is_some()
    }

    // Param is passed by value, moved
    pub fn set_Since(&mut self, v: u64) {
        self.Since = ::std::option::Option::Some(v);
    }

    // optional bool Recursive = 12;


    pub fn get_Recursive(&self) -> bool {
        self.Recursive.unwrap_or(false)
    }
    pub fn clear_Recursive(&mut self) {
        self.Recursive = ::std::option::Option::None;
    }

    pub fn has_Recursive(&self) -> bool {
        self.Recursive.is_some()
    }

    // Param is passed by value, moved
    pub fn set_Recursive(&mut self, v: bool) {
        self.Recursive = ::std::option::Option::Some(v);
    }

    // optional bool Sorted = 13;


    pub fn get_Sorted(&self) -> bool {
        self.Sorted.unwrap_or(false)
    }
    pub fn clear_Sorted(&mut self) {
        self.Sorted = ::std::option::Option::None;
    }

    pub fn has_Sorted(&self) -> bool {
        self.Sorted.is_some()
    }

    // Param is passed by value, moved
    pub fn set_Sorted(&mut self, v: bool) {
        self.Sorted = ::std::option::Option::Some(v);
    }

    // optional bool Quorum = 14;


    pub fn get_Quorum(&self) -> bool {
        self.Quorum.unwrap_or(false)
    }
    pub fn clear_Quorum(&mut self) {
        self.Quorum = ::std::option::Option::None;
    }

    pub fn has_Quorum(&self) -> bool {
        self.Quorum.is_some()
    }

    // Param is passed by value, moved
    pub fn set_Quorum(&mut self, v: bool) {
        self.Quorum = ::std::option::Option::Some(v);
    }

    // optional int64 Time = 15;


    pub fn get_Time(&self) -> i64 {
        self.Time.unwrap_or(0)
    }
    pub fn clear_Time(&mut self) {
        self.Time = ::std::option::Option::None;
    }

    pub fn has_Time(&self) -> bool {
        self.Time.is_some()
    }

    // Param is passed by value, moved
    pub fn set_Time(&mut self, v: i64) {
        self.Time = ::std::option::Option::Some(v);
    }

    // optional bool Stream = 16;


    pub fn get_Stream(&self) -> bool {
        self.Stream.unwrap_or(false)
    }
    pub fn clear_Stream(&mut self) {
        self.Stream = ::std::option::Option::None;
    }

    pub fn has_Stream(&self) -> bool {
        self.Stream.is_some()
    }

    // Param is passed by value, moved
    pub fn set_Stream(&mut self, v: bool) {
        self.Stream = ::std::option::Option::Some(v);
    }

    // optional bool Refresh = 17;


    pub fn get_Refresh(&self) -> bool {
        self.Refresh.unwrap_or(false)
    }
    pub fn clear_Refresh(&mut self) {
        self.Refresh = ::std::option::Option::None;
    }

    pub fn has_Refresh(&self) -> bool {
        self.Refresh.is_some()
    }

    // Param is passed by value, moved
    pub fn set_Refresh(&mut self, v: bool) {
        self.Refresh = ::std::option::Option::Some(v);
    }
}

impl ::protobuf::Message for Request {
    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream) -> ::protobuf::ProtobufResult<()> {
        while !is.eof()? {
            let (field_number, wire_type) = is.read_tag_unpack()?;
            match field_number {
                1 => {
                    if wire_type != ::protobuf::wire_format::WireTypeVarint {
                        return ::std::result::Result::Err(::protobuf::rt::unexpected_wire_type(wire_type));
                    }
                    let tmp = is.read_uint64()?;
                    self.ID = ::std::option::Option::Some(tmp);
                },
                2 => {
                    ::protobuf::rt::read_singular_string_into(wire_type, is, &mut self.Method)?;
                },
                3 => {
                    ::protobuf::rt::read_singular_string_into(wire_type, is, &mut self.Path)?;
                },
                4 => {
                    ::protobuf::rt::read_singular_string_into(wire_type, is, &mut self.Val)?;
                },
                5 => {
                    if wire_type != ::protobuf::wire_format::WireTypeVarint {
                        return ::std::result::Result::Err(::protobuf::rt::unexpected_wire_type(wire_type));
                    }
                    let tmp = is.read_bool()?;
                    self.Dir = ::std::option::Option::Some(tmp);
                },
                6 => {
                    ::protobuf::rt::read_singular_string_into(wire_type, is, &mut self.PrevValue)?;
                },
                7 => {
                    if wire_type != ::protobuf::wire_format::WireTypeVarint {
                        return ::std::result::Result::Err(::protobuf::rt::unexpected_wire_type(wire_type));
                    }
                    let tmp = is.read_uint64()?;
                    self.PrevIndex = ::std::option::Option::Some(tmp);
                },
                8 => {
                    if wire_type != ::protobuf::wire_format::WireTypeVarint {
                        return ::std::result::Result::Err(::protobuf::rt::unexpected_wire_type(wire_type));
                    }
                    let tmp = is.read_bool()?;
                    self.PrevExist = ::std::option::Option::Some(tmp);
                },
                9 => {
                    if wire_type != ::protobuf::wire_format::WireTypeVarint {
                        return ::std::result::Result::Err(::protobuf::rt::unexpected_wire_type(wire_type));
                    }
                    let tmp = is.read_int64()?;
                    self.Expiration = ::std::option::Option::Some(tmp);
                },
                10 => {
                    if wire_type != ::protobuf::wire_format::WireTypeVarint {
                        return ::std::result::Result::Err(::protobuf::rt::unexpected_wire_type(wire_type));
                    }
                    let tmp = is.read_bool()?;
                    self.Wait = ::std::option::Option::Some(tmp);
                },
                11 => {
                    if wire_type != ::protobuf::wire_format::WireTypeVarint {
                        return ::std::result::Result::Err(::protobuf::rt::unexpected_wire_type(wire_type));
                    }
                    let tmp = is.read_uint64()?;
                    self.Since = ::std::option::Option::Some(tmp);
                },
                12 => {
                    if wire_type != ::protobuf::wire_format::WireTypeVarint {
                        return ::std::result::Result::Err(::protobuf::rt::unexpected_wire_type(wire_type));
                    }
                    let tmp = is.read_bool()?;
                    self.Recursive = ::std::option::Option::Some(tmp);
                },
                13 => {
                    if wire_type != ::protobuf::wire_format::WireTypeVarint {
                        return ::std::result::Result::Err(::protobuf::rt::unexpected_wire_type(wire_type));
                    }
                    let tmp = is.read_bool()?;
                    self.Sorted = ::std::option::Option::Some(tmp);
                },
                14 => {
                    if wire_type != ::protobuf::wire_format::WireTypeVarint {
                        return ::std::result::Result::Err(::protobuf::rt::unexpected_wire_type(wire_type));
                    }
                    let tmp = is.read_bool()?;
                    self.Quorum = ::std::option::Option::Some(tmp);
                },
                15 => {
                    if wire_type != ::protobuf::wire_format::WireTypeVarint {
                        return ::std::result::Result::Err(::protobuf::rt::unexpected_wire_type(wire_type));
                    }
                    let tmp = is.read_int64()?;
                    self.Time = ::std::option::Option::Some(tmp);
                },
                16 => {
                    if wire_type != ::protobuf::wire_format::WireTypeVarint {
                        return ::std::result::Result::Err(::protobuf::rt::unexpected_wire_type(wire_type));
                    }
                    let tmp = is.read_bool()?;
                    self.Stream = ::std::option::Option::Some(tmp);
                },
                17 => {
                    if wire_type != ::protobuf::wire_format::WireTypeVarint {
                        return ::std::result::Result::Err(::protobuf::rt::unexpected_wire_type(wire_type));
                    }
                    let tmp = is.read_bool()?;
                    self.Refresh = ::std::option::Option::Some(tmp);
                },
                _ => {
                    ::protobuf::rt::read_unknown_or_skip_group(field_number, wire_type, is, self.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u32 {
        let mut my_size = 0;
        if let Some(v) = self.ID {
            my_size += ::protobuf::rt::value_size(1, v, ::protobuf::wire_format::WireTypeVarint);
        }
        if let Some(ref v) = self.Method.as_ref() {
            my_size += ::protobuf::rt::string_size(2, &v);
        }
        if let Some(ref v) = self.Path.as_ref() {
            my_size += ::protobuf::rt::string_size(3, &v);
        }
        if let Some(ref v) = self.Val.as_ref() {
            my_size += ::protobuf::rt::string_size(4, &v);
        }
        if let Some(v) = self.Dir {
            my_size += 2;
        }
        if let Some(ref v) = self.PrevValue.as_ref() {
            my_size += ::protobuf::rt::string_size(6, &v);
        }
        if let Some(v) = self.PrevIndex {
            my_size += ::protobuf::rt::value_size(7, v, ::protobuf::wire_format::WireTypeVarint);
        }
        if let Some(v) = self.PrevExist {
            my_size += 2;
        }
        if let Some(v) = self.Expiration {
            my_size += ::protobuf::rt::value_size(9, v, ::protobuf::wire_format::WireTypeVarint);
        }
        if let Some(v) = self.Wait {
            my_size += 2;
        }
        if let Some(v) = self.Since {
            my_size += ::protobuf::rt::value_size(11, v, ::protobuf::wire_format::WireTypeVarint);
        }
        if let Some(v) = self.Recursive {
            my_size += 2;
        }
        if let Some(v) = self.Sorted {
            my_size += 2;
        }
        if let Some(v) = self.Quorum {
            my_size += 2;
        }
        if let Some(v) = self.Time {
            my_size += ::protobuf::rt::value_size(15, v, ::protobuf::wire_format::WireTypeVarint);
        }
        if let Some(v) = self.Stream {
            my_size += 3;
        }
        if let Some(v) = self.Refresh {
            my_size += 3;
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.get_unknown_fields());
        self.cached_size.set(my_size);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream) -> ::protobuf::ProtobufResult<()> {
        if let Some(v) = self.ID {
            os.write_uint64(1, v)?;
        }
        if let Some(ref v) = self.Method.as_ref() {
            os.write_string(2, &v)?;
        }
        if let Some(ref v) = self.Path.as_ref() {
            os.write_string(3, &v)?;
        }
        if let Some(ref v) = self.Val.as_ref() {
            os.write_string(4, &v)?;
        }
        if let Some(v) = self.Dir {
            os.write_bool(5, v)?;
        }
        if let Some(ref v) = self.PrevValue.as_ref() {
            os.write_string(6, &v)?;
        }
        if let Some(v) = self.PrevIndex {
            os.write_uint64(7, v)?;
        }
        if let Some(v) = self.PrevExist {
            os.write_bool(8, v)?;
        }
        if let Some(v) = self.Expiration {
            os.write_int64(9, v)?;
        }
        if let Some(v) = self.Wait {
            os.write_bool(10, v)?;
        }
        if let Some(v) = self.Since {
            os.write_uint64(11, v)?;
        }
        if let Some(v) = self.Recursive {
            os.write_bool(12, v)?;
        }
        if let Some(v) = self.Sorted {
            os.write_bool(13, v)?;
        }
        if let Some(v) = self.Quorum {
            os.write_bool(14, v)?;
        }
        if let Some(v) = self.Time {
            os.write_int64(15, v)?;
        }
        if let Some(v) = self.Stream {
            os.write_bool(16, v)?;
        }
        if let Some(v) = self.Refresh {
            os.write_bool(17, v)?;
        }
        os.write_unknown_fields(self.get_unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn get_cached_size(&self) -> u32 {
        self.cached_size.get()
    }

    fn get_unknown_fields(&self) -> &::protobuf::UnknownFields {
        &self.unknown_fields
    }

    fn mut_unknown_fields(&mut self) -> &mut ::protobuf::UnknownFields {
        &mut self.unknown_fields
    }

    fn as_any(&self) -> &::std::any::Any {
        self as &::std::any::Any
    }
    fn as_any_mut(&mut self) -> &mut ::std::any::Any {
        self as &mut ::std::any::Any
    }
    fn into_any(self: Box<Self>) -> ::std::boxed::Box<::std::any::Any> {
        self
    }

    fn descriptor(&self) -> &'static ::protobuf::reflect::MessageDescriptor {
        Self::descriptor_static()
    }

    fn new() -> Request {
        Request::new()
    }

    fn descriptor_static() -> &'static ::protobuf::reflect::MessageDescriptor {
        static mut descriptor: ::protobuf::lazy::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::lazy::Lazy {
            lock: ::protobuf::lazy::ONCE_INIT,
            ptr: 0 as *const ::protobuf::reflect::MessageDescriptor,
        };
        unsafe {
            descriptor.get(|| {
                let mut fields = ::std::vec::Vec::new();
                fields.push(::protobuf::reflect::accessor::make_option_accessor::<_, ::protobuf::types::ProtobufTypeUint64>(
                    "ID",
                    |m: &Request| { &m.ID },
                    |m: &mut Request| { &mut m.ID },
                ));
                fields.push(::protobuf::reflect::accessor::make_singular_field_accessor::<_, ::protobuf::types::ProtobufTypeString>(
                    "Method",
                    |m: &Request| { &m.Method },
                    |m: &mut Request| { &mut m.Method },
                ));
                fields.push(::protobuf::reflect::accessor::make_singular_field_accessor::<_, ::protobuf::types::ProtobufTypeString>(
                    "Path",
                    |m: &Request| { &m.Path },
                    |m: &mut Request| { &mut m.Path },
                ));
                fields.push(::protobuf::reflect::accessor::make_singular_field_accessor::<_, ::protobuf::types::ProtobufTypeString>(
                    "Val",
                    |m: &Request| { &m.Val },
                    |m: &mut Request| { &mut m.Val },
                ));
                fields.push(::protobuf::reflect::accessor::make_option_accessor::<_, ::protobuf::types::ProtobufTypeBool>(
                    "Dir",
                    |m: &Request| { &m.Dir },
                    |m: &mut Request| { &mut m.Dir },
                ));
                fields.push(::protobuf::reflect::accessor::make_singular_field_accessor::<_, ::protobuf::types::ProtobufTypeString>(
                    "PrevValue",
                    |m: &Request| { &m.PrevValue },
                    |m: &mut Request| { &mut m.PrevValue },
                ));
                fields.push(::protobuf::reflect::accessor::make_option_accessor::<_, ::protobuf::types::ProtobufTypeUint64>(
                    "PrevIndex",
                    |m: &Request| { &m.PrevIndex },
                    |m: &mut Request| { &mut m.PrevIndex },
                ));
                fields.push(::protobuf::reflect::accessor::make_option_accessor::<_, ::protobuf::types::ProtobufTypeBool>(
                    "PrevExist",
                    |m: &Request| { &m.PrevExist },
                    |m: &mut Request| { &mut m.PrevExist },
                ));
                fields.push(::protobuf::reflect::accessor::make_option_accessor::<_, ::protobuf::types::ProtobufTypeInt64>(
                    "Expiration",
                    |m: &Request| { &m.Expiration },
                    |m: &mut Request| { &mut m.Expiration },
                ));
                fields.push(::protobuf::reflect::accessor::make_option_accessor::<_, ::protobuf::types::ProtobufTypeBool>(
                    "Wait",
                    |m: &Request| { &m.Wait },
                    |m: &mut Request| { &mut m.Wait },
                ));
                fields.push(::protobuf::reflect::accessor::make_option_accessor::<_, ::protobuf::types::ProtobufTypeUint64>(
                    "Since",
                    |m: &Request| { &m.Since },
                    |m: &mut Request| { &mut m.Since },
                ));
                fields.push(::protobuf::reflect::accessor::make_option_accessor::<_, ::protobuf::types::ProtobufTypeBool>(
                    "Recursive",
                    |m: &Request| { &m.Recursive },
                    |m: &mut Request| { &mut m.Recursive },
                ));
                fields.push(::protobuf::reflect::accessor::make_option_accessor::<_, ::protobuf::types::ProtobufTypeBool>(
                    "Sorted",
                    |m: &Request| { &m.Sorted },
                    |m: &mut Request| { &mut m.Sorted },
                ));
                fields.push(::protobuf::reflect::accessor::make_option_accessor::<_, ::protobuf::types::ProtobufTypeBool>(
                    "Quorum",
                    |m: &Request| { &m.Quorum },
                    |m: &mut Request| { &mut m.Quorum },
                ));
                fields.push(::protobuf::reflect::accessor::make_option_accessor::<_, ::protobuf::types::ProtobufTypeInt64>(
                    "Time",
                    |m: &Request| { &m.Time },
                    |m: &mut Request| { &mut m.Time },
                ));
                fields.push(::protobuf::reflect::accessor::make_option_accessor::<_, ::protobuf::types::ProtobufTypeBool>(
                    "Stream",
                    |m: &Request| { &m.Stream },
                    |m: &mut Request| { &mut m.Stream },
                ));
                fields.push(::protobuf::reflect::accessor::make_option_accessor::<_, ::protobuf::types::ProtobufTypeBool>(
                    "Refresh",
                    |m: &Request| { &m.Refresh },
                    |m: &mut Request| { &mut m.Refresh },
                ));
                ::protobuf::reflect::MessageDescriptor::new::<Request>(
                    "Request",
                    fields,
                    file_descriptor_proto()
                )
            })
        }
    }

    fn default_instance() -> &'static Request {
        static mut instance: ::protobuf::lazy::Lazy<Request> = ::protobuf::lazy::Lazy {
            lock: ::protobuf::lazy::ONCE_INIT,
            ptr: 0 as *const Request,
        };
        unsafe {
            instance.get(Request::new)
        }
    }
}

impl ::protobuf::Clear for Request {
    fn clear(&mut self) {
        self.ID = ::std::option::Option::None;
        self.Method.clear();
        self.Path.clear();
        self.Val.clear();
        self.Dir = ::std::option::Option::None;
        self.PrevValue.clear();
        self.PrevIndex = ::std::option::Option::None;
        self.PrevExist = ::std::option::Option::None;
        self.Expiration = ::std::option::Option::None;
        self.Wait = ::std::option::Option::None;
        self.Since = ::std::option::Option::None;
        self.Recursive = ::std::option::Option::None;
        self.Sorted = ::std::option::Option::None;
        self.Quorum = ::std::option::Option::None;
        self.Time = ::std::option::Option::None;
        self.Stream = ::std::option::Option::None;
        self.Refresh = ::std::option::Option::None;
        self.unknown_fields.clear();
    }
}

impl ::std::fmt::Debug for Request {
    fn fmt(&self, f: &mut ::std::fmt::Formatter) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for Request {
    fn as_ref(&self) -> ::protobuf::reflect::ProtobufValueRef {
        ::protobuf::reflect::ProtobufValueRef::Message(self)
    }
}

#[derive(PartialEq,Clone,Default)]
pub struct Metadata {
    // message fields
    NodeID: ::std::option::Option<u64>,
    ClusterID: ::std::option::Option<u64>,
    // special fields
    pub unknown_fields: ::protobuf::UnknownFields,
    pub cached_size: ::protobuf::CachedSize,
}

impl<'a> ::std::default::Default for &'a Metadata {
    fn default() -> &'a Metadata {
        <Metadata as ::protobuf::Message>::default_instance()
    }
}

impl Metadata {
    pub fn new() -> Metadata {
        ::std::default::Default::default()
    }

    // optional uint64 NodeID = 1;


    pub fn get_NodeID(&self) -> u64 {
        self.NodeID.unwrap_or(0)
    }
    pub fn clear_NodeID(&mut self) {
        self.NodeID = ::std::option::Option::None;
    }

    pub fn has_NodeID(&self) -> bool {
        self.NodeID.is_some()
    }

    // Param is passed by value, moved
    pub fn set_NodeID(&mut self, v: u64) {
        self.NodeID = ::std::option::Option::Some(v);
    }

    // optional uint64 ClusterID = 2;


    pub fn get_ClusterID(&self) -> u64 {
        self.ClusterID.unwrap_or(0)
    }
    pub fn clear_ClusterID(&mut self) {
        self.ClusterID = ::std::option::Option::None;
    }

    pub fn has_ClusterID(&self) -> bool {
        self.ClusterID.is_some()
    }

    // Param is passed by value, moved
    pub fn set_ClusterID(&mut self, v: u64) {
        self.ClusterID = ::std::option::Option::Some(v);
    }
}

impl ::protobuf::Message for Metadata {
    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream) -> ::protobuf::ProtobufResult<()> {
        while !is.eof()? {
            let (field_number, wire_type) = is.read_tag_unpack()?;
            match field_number {
                1 => {
                    if wire_type != ::protobuf::wire_format::WireTypeVarint {
                        return ::std::result::Result::Err(::protobuf::rt::unexpected_wire_type(wire_type));
                    }
                    let tmp = is.read_uint64()?;
                    self.NodeID = ::std::option::Option::Some(tmp);
                },
                2 => {
                    if wire_type != ::protobuf::wire_format::WireTypeVarint {
                        return ::std::result::Result::Err(::protobuf::rt::unexpected_wire_type(wire_type));
                    }
                    let tmp = is.read_uint64()?;
                    self.ClusterID = ::std::option::Option::Some(tmp);
                },
                _ => {
                    ::protobuf::rt::read_unknown_or_skip_group(field_number, wire_type, is, self.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u32 {
        let mut my_size = 0;
        if let Some(v) = self.NodeID {
            my_size += ::protobuf::rt::value_size(1, v, ::protobuf::wire_format::WireTypeVarint);
        }
        if let Some(v) = self.ClusterID {
            my_size += ::protobuf::rt::value_size(2, v, ::protobuf::wire_format::WireTypeVarint);
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.get_unknown_fields());
        self.cached_size.set(my_size);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream) -> ::protobuf::ProtobufResult<()> {
        if let Some(v) = self.NodeID {
            os.write_uint64(1, v)?;
        }
        if let Some(v) = self.ClusterID {
            os.write_uint64(2, v)?;
        }
        os.write_unknown_fields(self.get_unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn get_cached_size(&self) -> u32 {
        self.cached_size.get()
    }

    fn get_unknown_fields(&self) -> &::protobuf::UnknownFields {
        &self.unknown_fields
    }

    fn mut_unknown_fields(&mut self) -> &mut ::protobuf::UnknownFields {
        &mut self.unknown_fields
    }

    fn as_any(&self) -> &::std::any::Any {
        self as &::std::any::Any
    }
    fn as_any_mut(&mut self) -> &mut ::std::any::Any {
        self as &mut ::std::any::Any
    }
    fn into_any(self: Box<Self>) -> ::std::boxed::Box<::std::any::Any> {
        self
    }

    fn descriptor(&self) -> &'static ::protobuf::reflect::MessageDescriptor {
        Self::descriptor_static()
    }

    fn new() -> Metadata {
        Metadata::new()
    }

    fn descriptor_static() -> &'static ::protobuf::reflect::MessageDescriptor {
        static mut descriptor: ::protobuf::lazy::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::lazy::Lazy {
            lock: ::protobuf::lazy::ONCE_INIT,
            ptr: 0 as *const ::protobuf::reflect::MessageDescriptor,
        };
        unsafe {
            descriptor.get(|| {
                let mut fields = ::std::vec::Vec::new();
                fields.push(::protobuf::reflect::accessor::make_option_accessor::<_, ::protobuf::types::ProtobufTypeUint64>(
                    "NodeID",
                    |m: &Metadata| { &m.NodeID },
                    |m: &mut Metadata| { &mut m.NodeID },
                ));
                fields.push(::protobuf::reflect::accessor::make_option_accessor::<_, ::protobuf::types::ProtobufTypeUint64>(
                    "ClusterID",
                    |m: &Metadata| { &m.ClusterID },
                    |m: &mut Metadata| { &mut m.ClusterID },
                ));
                ::protobuf::reflect::MessageDescriptor::new::<Metadata>(
                    "Metadata",
                    fields,
                    file_descriptor_proto()
                )
            })
        }
    }

    fn default_instance() -> &'static Metadata {
        static mut instance: ::protobuf::lazy::Lazy<Metadata> = ::protobuf::lazy::Lazy {
            lock: ::protobuf::lazy::ONCE_INIT,
            ptr: 0 as *const Metadata,
        };
        unsafe {
            instance.get(Metadata::new)
        }
    }
}

impl ::protobuf::Clear for Metadata {
    fn clear(&mut self) {
        self.NodeID = ::std::option::Option::None;
        self.ClusterID = ::std::option::Option::None;
        self.unknown_fields.clear();
    }
}

impl ::std::fmt::Debug for Metadata {
    fn fmt(&self, f: &mut ::std::fmt::Formatter) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for Metadata {
    fn as_ref(&self) -> ::protobuf::reflect::ProtobufValueRef {
        ::protobuf::reflect::ProtobufValueRef::Message(self)
    }
}

static file_descriptor_proto_data: &'static [u8] = b"\
    \n-etcd/etcdserver/etcdserverpb/etcdserver.proto\x12\x0cetcdserverpb\x1a\
    \x14gogoproto/gogo.proto\"\x87\x04\n\x07Request\x12\x14\n\x02ID\x18\x01\
    \x20\x01(\x04R\x02IDB\x04\xc8\xde\x1f\0\x12\x1c\n\x06Method\x18\x02\x20\
    \x01(\tR\x06MethodB\x04\xc8\xde\x1f\0\x12\x18\n\x04Path\x18\x03\x20\x01(\
    \tR\x04PathB\x04\xc8\xde\x1f\0\x12\x16\n\x03Val\x18\x04\x20\x01(\tR\x03V\
    alB\x04\xc8\xde\x1f\0\x12\x16\n\x03Dir\x18\x05\x20\x01(\x08R\x03DirB\x04\
    \xc8\xde\x1f\0\x12\"\n\tPrevValue\x18\x06\x20\x01(\tR\tPrevValueB\x04\
    \xc8\xde\x1f\0\x12\"\n\tPrevIndex\x18\x07\x20\x01(\x04R\tPrevIndexB\x04\
    \xc8\xde\x1f\0\x12\"\n\tPrevExist\x18\x08\x20\x01(\x08R\tPrevExistB\x04\
    \xc8\xde\x1f\x01\x12$\n\nExpiration\x18\t\x20\x01(\x03R\nExpirationB\x04\
    \xc8\xde\x1f\0\x12\x18\n\x04Wait\x18\n\x20\x01(\x08R\x04WaitB\x04\xc8\
    \xde\x1f\0\x12\x1a\n\x05Since\x18\x0b\x20\x01(\x04R\x05SinceB\x04\xc8\
    \xde\x1f\0\x12\"\n\tRecursive\x18\x0c\x20\x01(\x08R\tRecursiveB\x04\xc8\
    \xde\x1f\0\x12\x1c\n\x06Sorted\x18\r\x20\x01(\x08R\x06SortedB\x04\xc8\
    \xde\x1f\0\x12\x1c\n\x06Quorum\x18\x0e\x20\x01(\x08R\x06QuorumB\x04\xc8\
    \xde\x1f\0\x12\x18\n\x04Time\x18\x0f\x20\x01(\x03R\x04TimeB\x04\xc8\xde\
    \x1f\0\x12\x1c\n\x06Stream\x18\x10\x20\x01(\x08R\x06StreamB\x04\xc8\xde\
    \x1f\0\x12\x1e\n\x07Refresh\x18\x11\x20\x01(\x08R\x07RefreshB\x04\xc8\
    \xde\x1f\x01\"L\n\x08Metadata\x12\x1c\n\x06NodeID\x18\x01\x20\x01(\x04R\
    \x06NodeIDB\x04\xc8\xde\x1f\0\x12\"\n\tClusterID\x18\x02\x20\x01(\x04R\t\
    ClusterIDB\x04\xc8\xde\x1f\0B\x10\xc8\xe1\x1e\0\xd0\xe2\x1e\x01\xc8\xe2\
    \x1e\x01\xe0\xe2\x1e\x01\
";

static mut file_descriptor_proto_lazy: ::protobuf::lazy::Lazy<::protobuf::descriptor::FileDescriptorProto> = ::protobuf::lazy::Lazy {
    lock: ::protobuf::lazy::ONCE_INIT,
    ptr: 0 as *const ::protobuf::descriptor::FileDescriptorProto,
};

fn parse_descriptor_proto() -> ::protobuf::descriptor::FileDescriptorProto {
    ::protobuf::parse_from_bytes(file_descriptor_proto_data).unwrap()
}

pub fn file_descriptor_proto() -> &'static ::protobuf::descriptor::FileDescriptorProto {
    unsafe {
        file_descriptor_proto_lazy.get(|| {
            parse_descriptor_proto()
        })
    }
}
